django/ams/urls.py
from core.views import GenericDeleteView
from core.views import HomeRedirectView
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", HomeRedirectView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("clients/", include("clients.urls")),
    path("delete/<str:app_label>/<str:model>/<uuid:pk>/", GenericDeleteView.as_view(), name="delete"),
    path("orders/", include("orders.urls.orders")),
    path("tasks/", include("tasks.urls.tasks")),
    path("task-types/", include("tasks.urls.task_type")),
]

django/orders/models.py
from core.models import AbstractBaseModel
from django.db import models
from django.db.models.query import QuerySet
from django.utils.translation import gettext_lazy as _
from tasks.models import Task


class Order(AbstractBaseModel):
    client = models.ForeignKey(verbose_name=_("Client"), to="clients.Client", on_delete=models.CASCADE)
    discount = models.FloatField(verbose_name=_("Discount"), null=True, blank=True)
    completed = models.BooleanField(verbose_name=_("Completed"), default=False)
    tasks = models.ManyToManyField(verbose_name=_("Services"), to="tasks.Task")
    due_date = models.DateField(verbose_name=_("Due Date"), null=True, blank=True)
    order_date = models.DateField(verbose_name=_("Order Date"), null=True, blank=True)

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    @property
    def total(self):
        tasks: QuerySet[Task, Task] = self.tasks.all()
        return sum([task.value for task in tasks])

django/orders/forms.py
from django import forms
from django.forms import ModelForm
from orders.models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ["client", "discount", "completed", "due_date", "order_date"]
        widgets = {
            "client": forms.Select(attrs={"class": "form-select"}),
            "discount": forms.NumberInput(attrs={"class": "form-control", "value": 0, "min": 0, "max": 100, "step": 1}),
            "completed": forms.CheckboxInput(attrs={"class": "form-check-input", "for": "completed"}),
            "due_date": forms.DateInput(attrs={"class": "form-control", "type": "date", "format": "%d/%m/%Y"}),
            "order_date": forms.DateInput(attrs={"class": "form-control", "type": "date", "format": "%d/%m/%Y"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if kwargs.get("instance") is not None:
            self.initial["order_date"] = self.instance.order_date.strftime("%Y-%m-%d")
            self.initial["due_date"] = self.instance.due_date.strftime("%Y-%m-%d")

django/orders/views/orders.py
import json
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models.query import QuerySet
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView
from orders.forms import OrderForm
from orders.models import Order
from tasks.forms import TaskFormSet
from tasks.models import Task


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = "orders/list.html"
    context_object_name = "orders"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_objects"] = Order.objects.count()
        return context


class OrderListJsonView(LoginRequiredMixin, ListView):
    model = Order

    def get_queryset(self):
        objects: QuerySet[Order, Order] = super().get_queryset()
        return objects

    def render_to_response(self, context: dict[str, Any], **response_kwargs: Any) -> HttpResponse:
        page_number = self.request.GET.get("page", 1)
        page_size = self.request.GET.get("pageSize", 10)

        paginator = Paginator(self.get_queryset(), page_size)
        page_obj = paginator.get_page(page_number)

        # Prepare data for Grid.js
        data = [
            {
                "client": obj.client.name,
                "due_date": str(obj.due_date),
                "order_date": str(obj.order_date),
                "total": float(obj.total),
                "completed": obj.completed,
                "discount": obj.discount,
                "id": str(obj.id),
            }
            for obj in page_obj
        ]

        response_data = {
            "data": data,
            "total": paginator.count,
        }

        return HttpResponse(json.dumps(response_data), content_type="application/json")


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "orders/detail.html"
    context_object_name = "order"


class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    template_name = "orders/form.html"
    success_url = reverse_lazy("orders:list")

    def get(self, request, *args, **kwargs):
        order_form = OrderForm()
        task_formset = TaskFormSet(queryset=Task.objects.none(), prefix="tasks")

        return render(request, self.template_name, {"form": order_form, "task_formset": task_formset})

    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        order_form = OrderForm(request.POST)
        task_formset = TaskFormSet(request.POST, prefix="tasks")

        if order_form.is_valid() and task_formset.is_valid():
            try:
                with transaction.atomic():
                    order = order_form.save()
                    tasks = task_formset.save(commit=False)
                    for task in tasks:
                        task.save()

                    order.tasks.add(*tasks)

                    for deleted_task in task_formset.deleted_objects:
                        deleted_task.delete()

                return redirect(self.success_url)
            except Exception as e:
                print(e)
                pass

        return render(request, self.template_name, {"form": order_form, "task_formset": task_formset})


class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    template_name = "orders/form.html"
    success_url = reverse_lazy("orders:list")

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        order_form = OrderForm(request.POST, instance=self.object)
        order_form = OrderForm(instance=self.object)
        task_formset = TaskFormSet(queryset=self.object.tasks.all(), prefix="tasks")

        return render(request, self.template_name, {"form": order_form, "task_formset": task_formset})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        order_form = OrderForm(request.POST, instance=self.object)
        task_formset = TaskFormSet(
            request.POST,
            prefix="tasks",
            queryset=self.object.tasks.all(),  # Use the correct related name
        )

        if order_form.is_valid() and task_formset.is_valid():
            try:
                with transaction.atomic():
                    order = order_form.save()

                    tasks = task_formset.save(commit=False)

                    for task in tasks:
                        task.save()

                    order.tasks.add(*tasks)

                    for deleted_task in task_formset.deleted_objects:
                        print(deleted_task)
                        deleted_task.delete()

                    return redirect(self.success_url)
            except Exception as e:
                print(f"Error: {e}")

        return render(request, self.template_name, {"form": order_form, "task_formset": task_formset})

django/orders/templates/orders/detail.html
{% extends 'layout.html' %} {% load i18n static %}

{% block title %}{% trans 'Orders' %} - {% trans 'Detail' %} {% endblock title %}

{% block page-title %}
<i class="bi bi-award mx-2"></i>
{% trans 'Orders' %} - {% trans 'Detail' %}
{% endblock page-title %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item active" aria-current="page">
    <a href="{% url 'orders:list' %}">{% trans 'List' %}</a>
  </li>
  <li class="breadcrumb-item">{% trans 'Detail' %}</li>
</ol>
{% endblock breadcrumb %}

{% block content %}

<div class="d-flex justify-content-end">
  <a href= "{% url 'orders:list' %}" class="btn btn-secondary mx-2">
    {% trans 'Back' %}
  </a>
  <a href= "{% url 'orders:update' order.id %}" class="btn btn-primary">
    <i class="bi bi-pencil"></i>
    {% trans 'Update' %}
  </a>
</div>

<div class="container m-0">
  <div class="row">
    <div class="col-md-8">
        <div class="card shadow">
            <div class="card-header bg-transparent border-secondary fs-5">{% trans 'Order' %}</div>
          <div class="card-body">
            <p class="card-text">
            <b>{% trans 'Client' %}:</b> {{ order.client.name }}<br/>
            </p>
            <p class="card-text">
              <b>{% trans 'Order Date' %}:</b> {{ order.order_date }}<br />
            </p>
            <p class="card-text">
              <b>{% trans 'Due Date' %}:</b> {{ order.due_date }}<br />
            </p>
            <p class="card-text">
              <b>{% trans 'Total' %}:</b> R$ {{ order.total }}<br />
            </p>
            <p class="card-text">
              <b>{% trans 'Completed' %}:</b> {{ order.completed|yesno }}<br />
            </p>
            <p class="card-text">
              <b>{% trans 'Discount' %}:</b> {{ order.discount }}%<br />
            </p>
          </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card shadow">
            <div class="card-header bg-transparent border-secondary fs-5">{% trans 'Tasks' %}</div>
          <div class="card-body">
            {% for task in order.tasks.all %}
              <p class="card-text"><b>{% trans 'Description' %}:</b> {{ task.description }} </p>
              <p class="card-text"><b>{% trans 'Value' %}:</b> R$ {{ task.value }} </p>
              <hr>
            {% endfor %}
          </div>
        </div>
    </div>
  </div>
</div>

{% endblock content %}

django/orders/templates/orders/form.html
{% extends 'layout.html' %} {% load i18n static %}

{% block title %}{% trans 'Orders' %} - {% trans 'Form' %} {% endblock title %}

{% block page-title %}
<i class="bi bi-award mx-2"></i>
{% trans 'Orders' %} - {% trans 'Form' %}
{% endblock page-title %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item active" aria-current="page">
    <a href="{% url 'orders:list' %}">{% trans 'List' %}</a>
  </li>
  <li class="breadcrumb-item">{% trans 'Form' %}</li>
</ol>
{% endblock breadcrumb %}

{% block content %}

<div class="container py-3">
<form method="post" novalidate>
  {% csrf_token %}
  <div class="row">
    <div class="col-md-12">

      <div class="card shadow">
        <div class="card-body">

            <div class="row">
            {% for field in form %}
            <div class="mb-3 col-md-6">

              {% if field.field.widget.input_type == 'checkbox' %}
              <div class="form-check">
                <label class="form-check-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <input class="form-check-input" type="checkbox" value="" id="{{ field.id_for_label }}" />
              </div>
              {% else %}
              <label for="{{ field.id_for_label }}" class="form-label">
                {{ field.label }}
              </label>
                {{ field }}
              {% endif %}

              {% if field.errors %}
              {% for error in field.errors %}
              <div class="invalid-feedback d-block">
                {{ error }}
              </div>
              {% endfor %}
              {% endif %}

              {% if field.help_text %}
              <small class="form-text text-muted">
                {{ field.help_text }}
              </small>
              {% endif %}
            </div>
            {% endfor %}

            <div class="d-flex mt-4 justify-content-end">
              <a href="{% url 'orders:list' %}" class="btn btn-secondary mx-2">
                {% trans 'Cancel' %}
              </a>
              <button type="submit" class="btn btn-success mx-2">
                {% trans 'Save' %}
              </button>
            </div>
            </div>
        </div>
      </div>

      <div class="card mb-3">
        <div class="card-header">
            <h5 class="card-title">Tasks</h5>
        </div>
        <div class="card-body">
            {# Important: Include the management form here #}
            {{ task_formset.management_form }}
            <div id="task-forms">
                {% for form in task_formset.forms %}
                    <div class="task-form mb-3">
                        {{ form.as_p }}
                        {% if task_formset.can_delete %}
                            <div class="form-check">
                                {{ form.DELETE }}
                                <label class="form-check-label">Delete this task</label>
                            </div>
                        {% endif %}
                        <hr>
                    </div>
                {% endfor %}
            </div>
            <button type="button" id="add-task" class="btn btn-secondary">Add Another Task</button>
        </div>
    </div>

    </div>
  </div>
  </form>
</div>

<script>
document.getElementById('add-task').addEventListener('click', function() {
    const forms = document.getElementsByClassName('task-form');
    const formNum = forms.length;
    const totalForms = document.querySelector('#id_tasks-TOTAL_FORMS');
    
    const newForm = forms[0].cloneNode(true);
    
    // Clear the values in the cloned form
    newForm.querySelectorAll('input:not([type=hidden])').forEach(input => {
        input.value = '';
    });
    newForm.querySelectorAll('select').forEach(select => {
        select.selectedIndex = 0;
    });
    
    // Update form index
    newForm.innerHTML = newForm.innerHTML.replace(
        /tasks-(\d+)-/g,
        function(match, p1) {
            return `tasks-${formNum}-`;
        }
    );
    
    document.getElementById('task-forms').appendChild(newForm);
    totalForms.value = formNum + 1;
});
</script>
{% endblock content %}

django/orders/templates/orders/list.html
{% extends 'layout.html' %} {% load i18n static %} 

{% block title %}{% trans 'Orders' %}{% endblock title %} 

{% block page-title %}
<i class="bi bi-award mx-2"></i>
{% trans 'Orders' %} 
{% endblock page-title %}

<link
  href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css"
  rel="stylesheet"
/>
<script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>


{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item active" aria-current="page">
    <a href="{% url 'orders:list' %}">{% trans 'List' %}</a>
  </li>
</ol>
{% endblock breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-sm-3">
    <div class="card text-bg-success mb-3" style="max-width: 18rem;">
      <div class="card-header text-center">{% trans 'Total Tasks' %}</div>
      <div class="card-body">
        <p class="card-text fs-5 text-center">{{ total_objects }}</p>
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-end">
  <a href= "{% url 'orders:create' %}" class="btn btn-success">
    <i class="bi bi-plus"></i>
    {% trans 'New Order' %}
  </a>
</div>

<div id="table" class="shadow row rounded-2 p-2 mt-3" data-url="{% url 'orders:json' %}"
  data-next-button-label="{% trans 'Next' %}"
  data-previous-button-label="{% trans 'Previous' %}"
  data-search-placeholder="{% trans 'Search...' %}"
  data-app-name="orders"
  data-model-name="order"></div>

<div id="modal-container"></div>
{% endblock content %} 

{% block js-external %}
<!-- <script src="{% static 'js/detail_modal.js' %}"></script> -->
<!-- <script src="{% static 'js/orders_list.js' %}"></script> -->
{% endblock js-external %}