django/ams/urls.py
from core.views import GenericDeleteView
from core.views import HomeRedirectView
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("", HomeRedirectView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("clients/", include("clients.urls")),
    path("delete/<str:app_label>/<str:model>/<uuid:pk>/", GenericDeleteView.as_view(), name="delete"),
    path("orders/", include("orders.urls.orders")),
    path("tasks/", include("tasks.urls.tasks")),
    path("task-types/", include("tasks.urls.task_type")),
]

django/clients/urls.py
from clients.views import ClientCreateView
from clients.views import ClientListHTMXView
from clients.views import ClientDetailView
from clients.views import ClientListView
from clients.views import ClientUpdateView
from clients.views import ClientStatsHTMXView
from django.urls import path

app_name = "clients"

urlpatterns = [
    path("", ClientListView.as_view(), name="list"),
    path("json/", ClientListHTMXView.as_view(), name="htmx"),
    path("stats/", ClientStatsHTMXView.as_view(), name="stats"),
    path("<uuid:pk>/", ClientDetailView.as_view(), name="detail"),
    path("create/", ClientCreateView.as_view(), name="create"),
    path("update/<uuid:pk>/", ClientUpdateView.as_view(), name="update"),
]

django/clients/models.py
from core.models import AbstractBaseModel
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxLengthValidator


class Address(models.Model):
    street = models.CharField(verbose_name=_("Street"), max_length=100, validators=[MaxLengthValidator(100)])
    number = models.IntegerField(verbose_name=_("Number"))
    neighborhood = models.CharField(
        verbose_name=_("Neighborhood"), max_length=100, validators=[MaxLengthValidator(100)]
    )
    city = models.CharField(verbose_name=_("City"), max_length=100, validators=[MaxLengthValidator(100)])

    def __str__(self):
        return f"{self.street}, {self.number}, {self.neighborhood} - {self.city}"


class Client(AbstractBaseModel):
    name = models.TextField(verbose_name=_("Name"), blank=False)
    phone = models.TextField(verbose_name=_("Phone"))
    annotations = models.TextField(verbose_name=_("Annotations"), blank=True)

    address = models.ForeignKey(Address, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}, {self.phone}, {self.annotations} - {self.address}"

    class Meta:
        verbose_name = _("Client")
        verbose_name_plural = _("Clients")
        ordering = ["created_at", "name"]

django/clients/forms.py
import re

from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Address
from .models import Client


class ClientForm(forms.ModelForm):
    street = forms.CharField(max_length=100, required=True)
    number = forms.IntegerField(required=True, min_value=1)
    neighborhood = forms.CharField(max_length=100, required=True)
    city = forms.CharField(max_length=100, required=True)

    class Meta:
        model = Client
        fields = ["name", "phone", "annotations", "street", "number", "neighborhood", "city"]

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        self.fields["number"].label = _("Number")
        self.fields["street"].label = _("Street")
        self.fields["neighborhood"].label = _("Neighborhood")
        self.fields["city"].label = _("City")

        if kwargs.get("instance") is not None:
            self.fields["number"].initial = self.instance.address.number
            self.fields["street"].initial = self.instance.address.street
            self.fields["neighborhood"].initial = self.instance.address.neighborhood
            self.fields["city"].initial = self.instance.address.city

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if not name:
            raise forms.ValidationError('O campo "Nome" não pode estar vazio.')
        return name

    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        if not phone:
            raise forms.ValidationError('O campo "Telefone" não pode estar vazio.')

        pattern = r"^\(\d{2}\)\s?\d{4,5}-\d{4}$"

        if not re.match(pattern, phone):
            raise forms.ValidationError("O telefone deve estar no formato (XX) XXXXX-XXXX.")
        return phone

    def save(self, commit=True):
        address = Address.objects.create(
            street=self.cleaned_data["street"],
            number=self.cleaned_data["number"],
            neighborhood=self.cleaned_data["neighborhood"],
            city=self.cleaned_data["city"],
        )

        client = super().save(commit=False)

        client.address = address

        if commit:
            client.save()

        return client

django/clients/views.py
import datetime as dt
from zoneinfo import ZoneInfo
from dateutil.relativedelta import relativedelta

from django.db.models import Q
from django.core.paginator import Page, Paginator
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from .forms import ClientForm
from .models import Client


class ClientListView(LoginRequiredMixin, TemplateView):
    template_name = "clients/list.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        page_number: int = self.request.GET.get("page", 1)
        clients = Client.objects.all()

        paginator: Paginator = Paginator(clients, self.paginate_by)
        page_obj: Page = paginator.get_page(page_number)

        context.update(
            {
                "page_obj": page_obj,
            }
        )

        return context


class ClientStatsHTMXView(LoginRequiredMixin, TemplateView):
    template_name = "clients/components/stats.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        total_clients = Client.objects.all()
        last_moth = dt.datetime.now(tz=ZoneInfo(settings.TIME_ZONE)).date() - relativedelta(months=1)

        context["total_clients"] = total_clients.count()
        context["total_new_clients"] = total_clients.filter(created_at__gte=last_moth).count()

        return context


class ClientListHTMXView(LoginRequiredMixin, ListView):
    model = Client
    template_name = "clients/components/rows.html"
    context_object_name = "clients"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        search = self.request.GET.get("search")
        clients = super().get_queryset()
        context = super().get_context_data(**kwargs)

        if search:
            clients = Client.objects.filter(Q(name__icontains=search))

        page_number: int = self.request.GET.get("page", 1)
        paginator: Paginator = Paginator(clients, self.paginate_by)
        page_obj: Page = paginator.get_page(page_number)

        context["clients"] = page_obj

        return context


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = "clients/detail.html"
    context_object_name = "client"


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    template_name = "clients/form.html"
    form_class = ClientForm
    success_url = reverse_lazy("clients:htmx")

    def form_valid(self, form):
        try:
            self.object = form.save()
            if not self._is_htmx_request():
                return super().form_valid(form)

            response = HttpResponse()
            response["HX-Trigger"] = "closeModal"
            return response

        except Exception as e:
            print(e)

    def _is_htmx_request(self):
        return self.request.headers.get("HX-Request") == "true"


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    template_name = "clients/form.html"
    form_class = ClientForm
    success_url = reverse_lazy("clients:htmx")

    def form_valid(self, form):
        try:
            self.object = form.save()
            if not self._is_htmx_request():
                return super().form_valid(form)

            response = HttpResponse()
            response["HX-Trigger"] = "closeModal"
            return response

        except Exception as e:
            print(e)

    def _is_htmx_request(self):
        return self.request.headers.get("HX-Request") == "true"

django/clients/templates/clients/client_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

django/clients/templates/clients/client_update.html
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Update" />
</form>

django/clients/templates/clients/cliente_create.html
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Save" />
</form>

django/clients/templates/clients/delete.html
{% load i18n %}

<form 
  method="post"
  hx-post="{% url 'clients:delete' object.pk %}"
  hx-target="#modal-content"
  hx-swap="innerHTML"
>
  {% csrf_token %}
  <h3 class="mb-4 text-center font-bold">{% trans 'Are you sure you want to delete?' %}</h3>
  <p class="mb-4 text-center">{{ object }}</p>
  <div class="modal-action">
    <button 
      type="submit"
      class="btn btn-success">
      {% trans 'Yes' %}
    </button>
  </div>
</form>

django/clients/templates/clients/detail.html
{% extends 'layout.html' %} {% load i18n static %}

{% block title %}{% trans 'Clients' %} - {% trans 'Detail' %} {% endblock title %}

{% block page-title %}
<i class="bi bi-award mx-2"></i>
{% trans 'Clients' %} - {% trans 'Detail' %}
{% endblock page-title %}

{% block breadcrumb %}
<div class="breadcrumbs text-sm">
  <ul>
    <li><a href="{% url 'clients:list' %}" class="link link-hover">{% trans 'List' %}</a></li>
    <li>{% trans 'Detail' %}</li>
  </ul>
</div>
{% endblock breadcrumb %}

{% block content %}

<div class="flex justify-end gap-2 mb-4">
  <a href="{% url 'clients:list' %}" class="btn btn-outline">
    {% trans 'Back' %}
  </a>
  <button hx-get="{% url 'clients:update' client.id %}" hx-target="#modal-content" hx-swap="innerHTML" onclick="modal.showModal()" class="btn btn-primary" disabled>
    <i class="bi bi-pencil mr-1"></i>
    {% trans 'Update' %}
  </button>
</div>

<div class="w-full">
  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div class="w-full">
      <div class="card bg-base-100 shadow-lg">
        <div class="card-header bg-base-200 border-b border-base-300 px-6 py-4">
          <h3 class="text-lg font-medium">{% trans 'Client Information' %}</h3>
        </div>
        <div class="card-body px-6 py-4">
          <div class="space-y-2">
            <p>
              <span class="font-semibold">{% trans 'Name' %}:</span> {{ client.name }}
            </p>
            <p>
              <span class="font-semibold">{% trans 'Phone' %}:</span> {{ client.phone }}
            </p>
            <p>
              <span class="font-semibold">{% trans 'Address' %}:</span> {{ client.address }}
            </p>
          </div>
          <div class="mt-4">
            <p>
              <span class="font-semibold">{% trans 'Annotations' %}:</span> {{ client.annotations }}
            </p>
          </div>
        </div>
        <div class="card-footer bg-base-200 border-t border-base-300 px-6 py-4">
          <p class="text-xs">
            <span class="font-semibold">{% trans 'Created At' %}:</span> {{ client.created_at }}
            <span class="font-semibold ml-2">{% trans 'Updated At' %}:</span> {{ client.updated_at }}
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<c-modal />

{% endblock content %}

django/clients/templates/clients/form.html
{% load i18n static %}

<form method="dialog">
  <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
</form>
<div class="py-3">
  {% if object.pk %}
    <h3 class="mb-4 text-center font-bold">{% trans 'Update Client' %}</h3>
  {% else %}
    <h3 class="mb-4 text-center font-bold">{% trans 'New Client' %}</h3>
  {% endif %}
  <form 
    method="post"
    novalidate
    {% if object.pk %}
      hx-post="{% url 'clients:update' object.pk %}"
    {% else %}
      hx-post="{% url 'clients:create' %}"
    {% endif %}
    hx-target="#modal-content"
    hx-swap="innerHTML"
  >
      {% csrf_token %}
      <div class="grid grid-cols-2 gap-4">

          {% for field in form %}
          <div class="form-control">
            <label 
              class="input w-full {% if field.errors %} input-error {% endif %}" 
              for="{{ field.id_for_label }}"
            >
              <span class="label">{{ field.label }}</span>
              <input 
                type="{{ field.field.widget.input_type }}" 
                name="{{ field.name }}" 
                id="{{ field.id_for_label }}"
                value="{{ field.value|default:'' }}" 
                {% if field.field.required %}required{% endif %}
                placeholder="{{ field.help_text|default:'' }}" />
              {% if field.field.required %}
                <span class="badge badge-secondary badge-xs">Required</span>
              {% else %}
                <span class="badge badge-neutral badge-xs">Optional</span>
              {% endif %}
            </label>

            <!-- {% if field.field.widget.input_type == 'checkbox' %} -->
            <!--     <label class="label cursor-pointer"> -->
            <!--       {{ field }} -->
            <!--       <span class="label-text">{{ field.label }}</span> -->
            <!--     </label> -->
            <!-- {% elif field.field.widget.input_type == 'textarea' %} -->
            <!--   <textarea  -->
            <!--     name="{{ field.name }}"  -->
            <!--     id="{{ field.id_for_label }}" -->
            <!--     class="textarea textarea-bordered {% if field.errors %}textarea-error{% endif %}" -->
            <!--     {% if field.field.required %}required{% endif %} -->
            <!--     placeholder="{{ field.help_text|default:'' }}">{{ field.value|default:'' }}</textarea> -->
            <!-- {% endif %} -->

            <!-- Display field errors -->
            {% if field.errors %}
              <div class="label">
                {% for error in field.errors %}
                  <span class="text-error">{{ error }}</span>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          {% endfor %}
    </div>
    <div class="modal-action">
      <button 
        type="submit"
        class="btn btn-success">
        {% trans 'Save' %}
      </button>
    </div>
  </form>
</div>

django/clients/templates/clients/list.html
{% extends 'layout.html' %} {% load i18n static %} 
{% block title %}{% trans 'Clients' %}{% endblock title %} 

{% block page-title %}
<i class="bi bi-award mx-2"></i>
{% trans 'Clients' %} 
{% endblock page-title %}

{% block breadcrumb %}
<c-breadcrumb-link href="{% url 'clients:list' %}" icon="bi bi-award" title="{% trans 'Clients'%}" ></c-breadcrumb-link>
{% endblock breadcrumb %} 

{% block content %}
<div
  class="stats shadow mx-3 my-2"
  hx-get="{% url 'clients:stats' %}"
  hx-trigger="load, refreshClients"
  hx-swap="innerHTML"
>
</div>

<div class="flex justify-end mb-2">
  <button 
    class="btn btn-success"
    onclick="modal.showModal()"
    hx-get="{% url 'clients:create' %}"
    hx-target="#modal-content"
    hx-swap="innerHTML"
  >
    <i class="bi bi-plus mr-2"></i>
    {% trans 'New Client' %}
  </button>
</div>

<c-table 
  :headers="['{% trans 'Name'%}', '{% trans 'Phone'%}', '{% trans 'Address' %}', '{% trans 'Actions' %}']"
  trigger="load, refreshClients"
  swap="innerHTML"
  url="{% url 'clients:htmx' %}?page={{ page_obj.number }}"
  app_htmx_url={% url 'clients:htmx' %}
  :attrs="page-obj"
/>

<c-modal />

<script>
  document.addEventListener("DOMContentLoaded", function () {

    document.body.addEventListener("htmx:afterRequest", function (event) {
      if (event.detail.xhr.status == 200 && event.detail.elt.tagName == "DIV") {
        console.log(event.detail.elt);
        htmx.trigger("#tbody", "refreshClients");
      }
    });

    document.body.addEventListener('closeModal', function() {
        document.getElementById('modal').close();
    });

  });
</script>
{% endblock content %} 